/run/initialize

/vis/open OFFSCREEN
/vis/drawVolume

/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set proton White
/vis/modeling/trajectories/drawByParticleID-0/set e- Yellow
/vis/modeling/trajectories/drawByParticleID-0/set G4CMPDriftElectron Violet
/vis/modeling/trajectories/drawByParticleID-0/set G4CMPDriftHole Orange
/vis/modeling/trajectories/drawByParticleID-0/set phononTS Red
/vis/modeling/trajectories/drawByParticleID-0/set phononTF Green
/vis/modeling/trajectories/drawByParticleID-0/set phononL Blue

/vis/viewer/set/style wireframe
/vis/viewer/set/hiddenMarker true

/g4cmp/producePhonons 1.0
/g4cmp/sampleLuke 1.0
/g4cmp/produceCharges 1.0

/gps/number 1
/gps/particle proton
/gps/pos/type Point
/gps/direction 0 -4 -1
/gps/pos/centre 0.0 0.5 0.56 cm
/gps/ene/type Mono
/gps/energy 120 GeV
/run/beamOn 1

# Top view (+Z axis looking down)
/vis/viewer/set/upVector 0 1 0
/vis/viewer/set/viewpointThetaPhi 0 0
/vis/viewer/zoom 1.6
/vis/ogl/set/printFilename proton_view_top
/vis/ogl/set/printMode pixmap
/vis/ogl/printEPS

# Side view (+X axis)
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/zoom 1.6
/vis/ogl/set/printFilename proton_view_side_x
/vis/ogl/set/printMode pixmap
/vis/ogl/printEPS

# Front view (+Y axis)
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 90 90
/vis/viewer/zoom 1.6
/vis/ogl/set/printFilename proton_view_side_y
/vis/ogl/set/printMode pixmap
/vis/ogl/printEPS
